# Generated by Django 6.0.1 on 2026-01-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='stock',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Barkod / SKU'),
        ),
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('adet', 'Adet'), ('kg', 'Kg'), ('mt', 'Metre')], default='adet', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
