# Generated by Django 6.0.1 on 2026-02-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_pricelist_priceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='subgroup',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
