# Generated by Django 6.0.1 on 2026-03-22 19:13

from django.db import migrations, models


def backfill_stock_identity(apps, schema_editor):
    Stock = apps.get_model('core_app', 'Stock')

    for stock in Stock.objects.all().iterator():
        name = (stock.name or '').strip()
        sku = (stock.sku or '').strip()
        subgroup = (stock.subgroup or '').strip()

        normalized_name = _normalize_text(name)
        stock.normalized_name = normalized_name
        stock.identity_key = _build_stock_identity_key(name, sku=sku, subgroup=subgroup)
        stock.save(update_fields=['normalized_name', 'identity_key'])


def _normalize_text(value):
    import re
    import unicodedata

    text = (value or '').strip()
    text = unicodedata.normalize('NFKD', text)
    text = ''.join(ch for ch in text if not unicodedata.combining(ch))
    text = text.casefold()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = ' '.join(text.split())
    return text


def _build_stock_identity_key(name, sku='', subgroup=''):
    normalized_sku = _normalize_text(sku)
    if normalized_sku:
        return f'sku:{normalized_sku}'

    normalized_name = _normalize_text(name)
    normalized_subgroup = _normalize_text(subgroup)
    return f'name:{normalized_name}|sub:{normalized_subgroup}'


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_stock_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='identity_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(backfill_stock_identity, migrations.RunPython.noop),
    ]
